from text_processor_functions import *
from text_processor import *

network_neuroscience = '''Despite substantial recent progress, our understanding of the principles and mechanisms underlying complex brain function and cognition remains incomplete. Network neuroscience proposes to tackle these enduring challenges. Approaching brain structure and function from an explicitly integrative perspective, network neuroscience pursues new ways to map, record, analyze and model the elements and interactions of neurobiological systems. Two parallel trends drive the approach: the availability of new empirical tools to create comprehensive maps and record dynamic patterns among molecules, neurons, brain areas and social systems; and the theoretical framework and computational tools of modern network science. The convergence of empirical and computational advances opens new frontiers of scientific inquiry, including network dynamics, manipulation and control of brain networks, and integration of network processes across spatiotemporal domains. We review emerging trends in network neuroscience and attempt to chart a path toward a better understanding of the brain as a multiscale networked system.'''

philosophy_neuroscience = '''Since its inception more than a quarter‐century ago, the philosophy of neuroscience has grown into a recognised field in the philosophy of the special sciences. It focusses on foundational issues in the discipline, but also anticipates developments in the neurosciences that bear on epistemological, ethical and cultural concerns. In this paper, life scientists are introduced to three current issues in the philosophy of neuroscience: a new version of the old reductionism‐versus‐integrationism debate, spurred recently by ‘new mechanist’ philosophers of neuroscience; a challenge to ‘dynamicist’ explanations in neuroscience, as either covertly mechanistic or nonexplanatory; and a brief introduction to the burgeoning field of neuroethics and neurolaw, which is finding new discoveries in neuroscience that bear on both familiar ethical debates and generate novel ethical and legal concerns.'''

AI_neuroscience = '''The fields of neuroscience and artificial intelligence (AI) have a long and intertwined history. In more recent times, however, communication and collaboration between the two fields has become less commonplace. In this article, we argue that better understanding biological brains could play a vital role in building intelligent machines. We survey historical interactions between the AI and neuroscience fields and emphasize current advances in AI that have been inspired by the study of neural computation in humans and other animals. We conclude by highlighting shared themes that may be key for advancing future research in both fields.'''

seductive_neuroscience = '''Explanations of psychological phenomena seem to generate more public interest when they contain neuroscientific information. Even irrelevant neuroscience information in an explanation of a psychological phenomenon may interfere with people's abilities to critically consider the underlying logic of this explanation. We tested this hypothesis by giving naïve adults, students in a neuroscience course, and neuroscience experts brief descriptions of psychological phenomena followed by one of four types of explanation, according to a 2 (good explanation vs. bad explanation) × 2 (without neuroscience vs. with neuroscience) design. Crucially, the neuroscience information was irrelevant to the logic of the explanation, as confirmed by the expert subjects. Subjects in all three groups judged good explanations as more satisfying than bad ones. But subjects in the two nonexpert groups additionally judged that explanations with logically irrelevant neuroscience information were more satisfying than explanations without. The neuroscience information had a particularly striking effect on nonexperts' judgments of bad explanations, masking otherwise salient problems in these explanations.'''

list_of_docs = [network_neuroscience, philosophy_neuroscience, AI_neuroscience, seductive_neuroscience]

sentences_docs = [sentence_segment(x) for x in list_of_docs]

sentences_docs